### PR TITLE
Set up react

### PR DESCRIPTION
**Pull request by pedrovgs**
### :tophat: What is the goal?

Add [React](https://reactjs.org/) to the project to be able to develop this electron application using this framework.

### How is it being implemented?

As by default electron does not support hot swapping I've decided to configure this project using React and [webpack dev server](https://github.com/webpack/docs/wiki/webpack-dev-server) pointing the electron environment to ``localhost:3000`` instead of loading the built file. This let me develop the electron app as if coding any web page. By improving the feedback loop we will improve the time needed to review if a change is implemented properly. [This](https://medium.freecodecamp.org/building-an-electron-application-with-create-react-app-97945861647c) tutorial was really helpful. Additionally, I've added some dependencies we are going to use during the next development iterations:

* [electron-store](https://github.com/sindresorhus/electron-store): At some point, we will have to persist something, so I guess this will be helpful.
* [monet](https://monet.github.io/monet.js/): Let's use some powerful functional programming abstractions.
* [monet](https://momentjs.com/): Halding time is always a pain in the ass 😄 
* [jsverify](jsverify.github.io): If we use functional programming we will have to use property-based testing 👍 

As debugging and reviewing the state of the app is also important, I've configured this project to automatically install the react and redux developer tools chrome extensions while starting the app. The usage of these chrome extensions is going to be crucial during the project development.

This is the current state of the app:

screen shot 2018-03-03 at 20 45 14

An electron application loading a react app served using webpack-dev-server 😃 

### How can it be tested?

Automatically! :robot: I've added some automated tests I'd recommend you to review :smiley:

### CODE REVIEW

**Comment by JorgeCastilloPrz** [comment]
Hi @pedrovgs. I'm trying to follow this project to learn about this stack. Interestingly I've been trying to setup webpack this morning with no big luck (until I discovered this webpack config line to avoid some webpack errors `exclude: /(node_modules|bower_components)/,)`. 

Then I found out this PR from yesterday which is really clarifying for a lot of doubts I had.  One little question: Is the `electron-wait-react.js` something you need for Heroku? I am missing that on the PR description but seems like you're also preparing this to run on heroku.

Also found out that you are forced to create a `public` folder and add `index.html` inside so it can be loaded. Do you know more about the rationale behind that? Is it possible to configure react to let it find it in a different directory?

Thanks for the very detailed step by step project!

**Comment by pedrovgs** [comment]
Hi @JorgeCastilloPrz thanks for your comments 😃 

I'm not using Heroku and I don't plan to use it. This repository contains an electron app and I don't need to serve from any web application or from Heroku. This PR contains two major features:

* React set up and configuration.
* Configure ``webpack-dev-server`` to serve the application locally in order to be able to develop the electron app without restarting the app after every change. **The usage of ``webpack-dev-server`` is just needed for development purposes.**

About the public folder and the ``index.html`` file, this is just the file which is going to be loaded by default in our React application. That's why the name is ``index.html``. If I'm not wrong, this is the default place where our react scripts attach the final bundle created by ``webpack`` when the js code is evaluated on "build time". I guess you can review the React documentation in order to find if you can customize this. But I don't think is worth it, but you can give it a try.  If you don't find any related to this topic remember you can always try to build the app manually using ``webpack`` and create a file named ``whatever.html`` with the hadrcoded path to the ``bundle.js`` generated by webpack. You can find an example [here](https://github.com/pedrovgs/HaveANiceDayChromeExtension)

I'll continue sending PRs for this project explaining the evolution of the code and the libraries or technologies used. Feel free to comment or ask whatever you want 😃 Have a nice day!

**Comment by JorgeCastilloPrz** [comment]
Alright thanks! :). What is `electron-wait-react.js` for then ?

**Comment by JorgeCastilloPrz** [comment]
Also I don't see that you're adding `style-loader` nor `css-loader` to webpack plugins but you seem to be using css here. How did you get it to work through webpack ? I needed to add those as you can see [here](https://github.com/JorgeCastilloPrz/ElectronSample/blob/master/webpack.config.js#L33) and still I get runtime javascript issues with css, can't get it to work for random reasons. The app works but just when you comment the css import / requires :/

**Comment by pedrovgs** [comment]
``electron-wait-react.js`` script is invoked from the ``Procfile`` config file and is used too coordinate the webpack-dev-server process startup and the electron process startup when running ``yarn run dev``. This is helpful if you don't want to run webpack manually and wait for the server to start and then run electron.

About the style-loader dependency. This is configured by the react-scripts when adding react to the project. I did not configure the css/style loader for webpack. Thanks to ``react-scripts`` dependencies I can forget about this part of the configuration.

**Comment by JorgeCastilloPrz** [comment]
Now that makes a lot of sense. I wasn't using `react-scripts` so I was building the webpack server manually (through the run dev script [here](https://github.com/JorgeCastilloPrz/ElectronSample/blob/master/package.json#L13) which wakes up th e server in dev mode) and launching the electron app afterwards. 

Thanks for your answers!

**Comment by JorgeCastilloPrz** [comment]
I've got this already running following what you did, but for some reason I get the project deployed to browser with both commands (`yarn start` and `yarn run dev`). This is the console output I get for the later:

captura de pantalla 2018-03-04 a las 17 42 43

[The code, in case you wanna help :D](https://github.com/JorgeCastilloPrz/ElectronSample/pull/1)

**Comment by pedrovgs** [comment]
Using webpack-dev-server you are going to get always the project open on your default browser. That's the default behavior implemented by webpack-dev-server. I'm not sure if you can change this. If you execute just ``yarn start`` you'll see your app on the browser (the expected behavior). But, if you run ``yarn run dev`` you should see your app starting on the browser and after that, you should see the electron app up and running loading your app from ``localhost:300``.

After cloning your repository and checking what's going on I've found your issue. Your ``Procfile.txt`` should be renamed to ``Procfile``. By just removing the file extension you'll see the electron app up and running. Let me know if this is the fix you were looking for.

**Comment by JorgeCastilloPrz** [comment]
Oh! There you go. Thanks for cloning though, I was starting to get crazy on
this.

**Pull request merged**
